{% set PYTHON = "python3" %}
{% set name = "pytiff" %}
{% set version = "0.8.0" %}
package:
  name: "{{ name|lower }}"
  version: "{{ version }}"
source:
  git_url: https://github.com/FZJ-INM1-BDA/pytiff.git
  git_rev: {{ version }}
build:
  number: 0
  script: "pip install --upgrade pip; pip install pytiff"
requirements:
  host:
  build: 
    - pip
  run:
test:
about:
  home: ""
  license:
  summary: ""
